# .project metadata for Open Policy Agent (OPA)
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

schema_version: "1.0.0"
slug: "open-policy-agent"
name: "Open Policy Agent (OPA)"
description: "An open source, general-purpose policy engine"
type: "project"
project_lead: "johanfylling"
slack_channels:
  - link: "https://slack.openpolicyagent.org/"

maturity_log:
  - phase: "graduated"
    date: "2018-03-29T00:00:00Z"
    issue: "https://github.com/cncf/toc/issues/51" # TODO: AUTO-DETECTED — please verify

repositories:
  - url: "https://github.com/open-policy-agent/opa"
    primary: true
    # tags: [core, sig-apps] # Optional

website: "https://www.openpolicyagent.org/"

artwork: "https://raw.githubusercontent.com/cncf/artwork/refs/heads/main/projects/open-policy-agent/stacked/color/opa-stacked-color.svg"

adopters:
  path: "https://github.com/open-policy-agent/opa/blob/main/ADOPTERS.md"


package_managers:
  docker:
    - "openpolicyagent/opa"
    - "openpolicyagent/opa-wasm-builder"
    - "openpolicyagent/proxy_init"
    - "openpolicyagent/opa-control-plane"
    - "openpolicyagent/conftest"
    - "openpolicyagent/kube-mgmt"
    - "ghcr.io/open-policy-agent/regal"
    - "ghcr.io/open-policy-agent/kube-mgmt"
    - "ghcr.io/open-policy-agent/opa-docker-authz"
    - "openpolicyagent/gatekeeper"
    - "openpolicyagent/gatekeeper-crds"
    - "openpolicyagent/gator"
    - "ghcr.io/open-policy-agent/gatekeeper"
    - "ghcr.io/open-policy-agent/gatekeeper-crds"
    - "ghcr.io/open-policy-agent/gator"
  homebrew:
    - "opa"
    - "regal"
    - "gator"
  npm:
    - "@open-policy-agent/opa-wasm"
    - "@open-policy-agent/opa"
    - "@open-policy-agent/opa-react"
    - "@open-policy-agent/ucast-prisma"

social:
  twitter: "https://twitter.com/openpolicyagent"

security:
  policy:
    path: "https://github.com/open-policy-agent/opa/blob/main/SECURITY.md"
  contact:
    advisory_url: "https://github.com/open-policy-agent/opa/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/open-policy-agent/opa/blob/main/CONTRIBUTING.md"
  code_of_conduct:
    path: "https://github.com/open-policy-agent/opa/blob/main/CODE_OF_CONDUCT.md"

legal:
  license:
    path: "https://github.com/open-policy-agent/opa/blob/main/LICENSE"
  identity_type:
    has_dco: true # AUTO-DETECTED — please verify
    has_cla: false # AUTO-DETECTED — please verify
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/open-policy-agent/opa/blob/main/README.md"

landscape:
  category: "Provisioning"
  subcategory: "Security & Compliance"

# CLOMonitor Score: 85/100
# Documentation: 94 | License: 90 | Best Practices: 69 | Security: 68
